spring:
  profiles:
    active: beta
  main:
    bannerMode: "off"
mybatis:
   mapperLocations: classpath:/mappers/*.xml
   typeAliasesPackage: com.pierce.data.dao
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
