server:
  port: 8088
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stat?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
debug: true
salt: test
