server:
  session:
    cookie:
      name: "YYYBSESSIONID"
spring:
  profiles:
    active: dev
  main:
    bannerMode: "off"
  mvc:
    view:
      suffix: .html
      prefix: /
mybatis:
   mapperLocations: classpath:/mappers/*.xml
   typeAliasesPackage: com.pierce.data.dao
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
