package com.pierce.data.dao;

import com.pierce.data.pojo.Permission;
import com.pierce.data.vo.MenuPermissionVo;
import com.pierce.data.vo.UserPermissionVo;

import java.util.List;
import java.util.Set;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated
     */
    Permission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated
     */
    List<Permission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Permission record);

    UserPermissionVo getUserPermissions(String username);

    Set<String> getAllMenu();

    Set<String> getAllPermissionCodes();

    Set<MenuPermissionVo> getAllMenuPermissions();
}