package com.pierce.data.dao;

import com.pierce.data.pojo.User;
import com.pierce.data.vo.UserInfoVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    User selectUserByUserName(String username);

    List<UserInfoVo> selectUserInfoList(@Param("pageStart")int pageStart, @Param("pageSize")int pageSize);

    int queryExistByUserName(String username);

    int countUser();

    int updateByPrimaryKeySelective(@Param("userId") Integer userId, @Param("nickname") String nickname, @Param("password") String password, @Param("roleId") Integer roleId);
}